language: php

php:
  - 7.0
  - 7.1

before_script:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-de language-pack-fr
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit

sudo: false

cache:
  bundler: true
  directories:
  - vendor

notifications:
    on_success: never
    on_failure: always